services:
  mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_DATABASE: account_service_db
      MYSQL_USER: nexus
      MYSQL_PASSWORD: nexus123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - '3307:3306'